source "https://supermarket.chef.io"

metadata

cookbook 'atom', '~> 0.1.1'
cookbook 'gimp', '~> 1.1.0'
cookbook 'skype-app', '~> 0.2.0'
cookbook 'steam', '~> 2.0.0'
cookbook 'virtualbox', '~> 0.6.1'
