source "https://supermarket.chef.io"

metadata

cookbook 'atom', '~> 0.1.1'
cookbook 'chrome', '~> 1.1.1'
cookbook 'gimp', '~> 1.1.0'
cookbook 'git', '~> 4.3.7'
cookbook 'skype-app', '~> 0.2.0'
cookbook 'steam', '~> 2.0.0'
cookbook 'virtualbox', '~> 0.6.1'
cookbook 'winbox', '~> 0.9.101'
cookbook 'windows', '~> 1.39.2'
