name              'lukecarrier'
maintainer        'Luke Carrier'
maintainer_email  'luke@carrier.im'
license           'GPLv3'
description       'Configures Ubuntu systems with no additional effort necessary'
long_description  File.join(File.dirname(__FILE__), 'README.md')
version           '0.0.1'

depends 'ark'
depends 'atom'
depends 'chocolatey'
depends 'chrome'
depends 'gimp'
depends 'git'
depends 'nvm-ng'
depends 'skype-app'
depends 'steam'
depends 'vagrant'
depends 'virtualbox'
depends 'winbox'
depends 'windows'

supports 'ubuntu'
supports 'windows'
