#!/usr/bin/env bash

# Preserve x lines of history in .bash_history
HISTFILESIZE=10000

# Load x lines into shell
HISTSIZE=5000

# Append to, don't overwrite, the file
shopt -s histappend

# Write changes incrementally (append to file and reload in-shell history)
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
